version: '3.9'
services:
  website:
    build: .
    volumes:
      - .:/app # Mount the project directory
      - node_modules:/app/node_modules # Use a named volume for node_modules
    ports:
      - "5173:5173" # Map Vite's default port
    stdin_open: true # Keep STDIN open for interactive shell
    tty: true        # Allocate a pseudo-TTY
    command: sh      # Override CMD to open shell automatically
    environment:
      - NODE_ENV=development
    working_dir: /app

volumes:
  node_modules: # Declare named volume for node_modules
