version: '3.9'
services:
  website:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules  # Use named volume for node_modules
    ports:
      - "5173:5173" # Map Vite's default port
    stdin_open: true # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY
    command: sh
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app

volumes: #volumes to persist even after docker-compose down, defining the volumes explicitly
  node_modules: