version: '3.9'
services:
  website:
    build: .
    volumes:
      - .:/app
      - /app/node_modules # Avoid syncing node_modules
    ports:
      - "5173:5173" # Map Vite's default port
    stdin_open: true # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY
    environment:
      - NODE_ENV=development
    working_dir: /app